# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([3, 6, 1, 9, 0, 9, 6, 4, 8, 5])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[97, 82, 36, 70, 90],
       [18, 28, 53, 86, 17],
       [38, 65, 79,  3,  6],
       [25, 24, 60, 39, 87]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.46032488, 0.33298909, 0.86686981, 0.7606226 , 0.35239293],
        [0.15765196, 0.96108596, 0.28130569, 0.24134874, 0.15113475],
        [0.7214775 , 0.42729345, 0.99374151, 0.80638173, 0.55602544],
        [0.76430951, 0.17702435, 0.66095263, 0.57059273, 0.46686146]],

       [[0.97886277, 0.04606383, 0.94462627, 0.61607666, 0.31013303],
        [0.78908856, 0.66630928, 0.16967462, 0.38152104, 0.34414229],
        [0.83558829, 0.35877958, 0.30053251, 0.31186175, 0.22891755],
        [0.82027126, 0.60532199, 0.85892761, 0.00843972, 0.73884935]],

       [[0.32314999, 0.54875907, 0.61465537, 0.73875642, 0.88581486],
        [0.85378851, 0.39199683, 0.20125733, 0.25968812, 0.97400005],
        [0.84213166, 0.93767322, 0.20631092, 0.11203554, 0.13732836],
        [0.44203955, 0.73617698, 0.35940857, 0.12558291, 0.12356086]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'