# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([1, 3, 9, 3, 0, 3, 9, 5, 2, 3])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[ 19,   4,  14,  10,  95],
       [ 30,  65,  78, 100,  77],
       [ 81,  56,  46,  99,  99],
       [ 34,  87,  28,  94,  90]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.54539607, 0.2006384 , 0.3332248 , 0.72778316, 0.1816849 ],
        [0.99912861, 0.3753253 , 0.12319861, 0.86900372, 0.47174463],
        [0.66013702, 0.4119241 , 0.80137192, 0.12891798, 0.47242092],
        [0.37387668, 0.71586219, 0.96144984, 0.62696955, 0.69648516]],

       [[0.36881189, 0.84550528, 0.45949837, 0.21449398, 0.85414894],
        [0.54114496, 0.10191007, 0.60787885, 0.59469594, 0.14984536],
        [0.41484798, 0.36043992, 0.1893149 , 0.66636484, 0.25940823],
        [0.31649411, 0.41305583, 0.05482618, 0.94173899, 0.41826893]],

       [[0.59724214, 0.72981605, 0.41469711, 0.4922534 , 0.55826983],
        [0.44268431, 0.90435483, 0.8754921 , 0.59899955, 0.5341011 ],
        [0.06873466, 0.09367422, 0.1702164 , 0.59879118, 0.80384419],
        [0.76987708, 0.87205879, 0.37017521, 0.43225566, 0.85086742]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([1, 3, 9, 3, 0, 3, 9, 5, 2, 3])

In [6]:
# nome_do_array[índice]
a1D[0]

1

In [7]:
a1D[2]

9

In [8]:
a1D[-1]

3

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([3, 1, 3])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[ 19,   4,  14,  10,  95],
       [ 30,  65,  78, 100,  77],
       [ 81,  56,  46,  99,  99],
       [ 34,  87,  28,  94,  90]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

78

In [12]:
a2D[3][4]

90

In [13]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([19, 65, 46, 94])

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([10, 78, 56, 34])

In [15]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([94, 46, 65, 19])

In [16]:
a2D[:,[0,1,2,0]] 

array([[19,  4, 14, 19],
       [30, 65, 78, 30],
       [81, 56, 46, 81],
       [34, 87, 28, 34]])

In [17]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[30, 65, 78, 30],
       [19,  4, 14, 19],
       [30, 65, 78, 30],
       [19,  4, 14, 19]])

In [18]:
a2D

array([[ 19,   4,  14,  10,  95],
       [ 30,  65,  78, 100,  77],
       [ 81,  56,  46,  99,  99],
       [ 34,  87,  28,  94,  90]])

In [19]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[30, 65, 78, 30],
       [19,  4, 14, 19],
       [30, 65, 78, 30],
       [19,  4, 14, 19]])

In [20]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.54539607, 0.2006384 , 0.3332248 , 0.72778316, 0.1816849 ],
        [0.99912861, 0.3753253 , 0.12319861, 0.86900372, 0.47174463],
        [0.66013702, 0.4119241 , 0.80137192, 0.12891798, 0.47242092],
        [0.37387668, 0.71586219, 0.96144984, 0.62696955, 0.69648516]],

       [[0.36881189, 0.84550528, 0.45949837, 0.21449398, 0.85414894],
        [0.54114496, 0.10191007, 0.60787885, 0.59469594, 0.14984536],
        [0.41484798, 0.36043992, 0.1893149 , 0.66636484, 0.25940823],
        [0.31649411, 0.41305583, 0.05482618, 0.94173899, 0.41826893]],

       [[0.59724214, 0.72981605, 0.41469711, 0.4922534 , 0.55826983],
        [0.44268431, 0.90435483, 0.8754921 , 0.59899955, 0.5341011 ],
        [0.06873466, 0.09367422, 0.1702164 , 0.59879118, 0.80384419],
        [0.76987708, 0.87205879, 0.37017521, 0.43225566, 0.85086742]]])

In [21]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.49225339716378913

In [22]:
a3D[0][3][1]

0.7158621931829816

### Fatiamento (slicing)

In [23]:
# Array de 1 dimensão
a1D

array([1, 3, 9, 3, 0, 3, 9, 5, 2, 3])

In [24]:
a = a1D[1:5] # Índice 1 ao 4
a

array([3, 9, 3, 0])

In [25]:
b = a1D[0:6] # Índice 0 ao 5
b

array([1, 3, 9, 3, 0, 3])

In [26]:
c = a1D[:6] # Do início ao 5
c

array([1, 3, 9, 3, 0, 3])

In [27]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([1, 9, 0, 9, 2])

In [28]:
e = a1D[-1::-1] # Do final até o início
e

array([3, 2, 5, 9, 3, 0, 3, 9, 3, 1])

In [29]:
# Array de 2 dimensões
a2D

array([[ 19,   4,  14,  10,  95],
       [ 30,  65,  78, 100,  77],
       [ 81,  56,  46,  99,  99],
       [ 34,  87,  28,  94,  90]])

In [30]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([19,  4, 14, 10, 95])

In [31]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([ 30,  65,  78, 100,  77])

In [32]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([56, 46, 99])

In [33]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([34, 87, 28, 94, 90])

In [34]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([14, 78, 46, 28])

In [35]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([100,  99,  94])

In [36]:
# Array de 3 dimensões
a3D

array([[[0.54539607, 0.2006384 , 0.3332248 , 0.72778316, 0.1816849 ],
        [0.99912861, 0.3753253 , 0.12319861, 0.86900372, 0.47174463],
        [0.66013702, 0.4119241 , 0.80137192, 0.12891798, 0.47242092],
        [0.37387668, 0.71586219, 0.96144984, 0.62696955, 0.69648516]],

       [[0.36881189, 0.84550528, 0.45949837, 0.21449398, 0.85414894],
        [0.54114496, 0.10191007, 0.60787885, 0.59469594, 0.14984536],
        [0.41484798, 0.36043992, 0.1893149 , 0.66636484, 0.25940823],
        [0.31649411, 0.41305583, 0.05482618, 0.94173899, 0.41826893]],

       [[0.59724214, 0.72981605, 0.41469711, 0.4922534 , 0.55826983],
        [0.44268431, 0.90435483, 0.8754921 , 0.59899955, 0.5341011 ],
        [0.06873466, 0.09367422, 0.1702164 , 0.59879118, 0.80384419],
        [0.76987708, 0.87205879, 0.37017521, 0.43225566, 0.85086742]]])

In [37]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.36881189, 0.84550528, 0.45949837, 0.21449398, 0.85414894],
       [0.54114496, 0.10191007, 0.60787885, 0.59469594, 0.14984536],
       [0.41484798, 0.36043992, 0.1893149 , 0.66636484, 0.25940823],
       [0.31649411, 0.41305583, 0.05482618, 0.94173899, 0.41826893]])

In [38]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.84550528, 0.45949837, 0.21449398],
       [0.10191007, 0.60787885, 0.59469594],
       [0.36043992, 0.1893149 , 0.66636484]])

In [39]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.66013702, 0.4119241 , 0.80137192, 0.12891798, 0.47242092])

In [40]:
a3D

array([[[0.54539607, 0.2006384 , 0.3332248 , 0.72778316, 0.1816849 ],
        [0.99912861, 0.3753253 , 0.12319861, 0.86900372, 0.47174463],
        [0.66013702, 0.4119241 , 0.80137192, 0.12891798, 0.47242092],
        [0.37387668, 0.71586219, 0.96144984, 0.62696955, 0.69648516]],

       [[0.36881189, 0.84550528, 0.45949837, 0.21449398, 0.85414894],
        [0.54114496, 0.10191007, 0.60787885, 0.59469594, 0.14984536],
        [0.41484798, 0.36043992, 0.1893149 , 0.66636484, 0.25940823],
        [0.31649411, 0.41305583, 0.05482618, 0.94173899, 0.41826893]],

       [[0.59724214, 0.72981605, 0.41469711, 0.4922534 , 0.55826983],
        [0.44268431, 0.90435483, 0.8754921 , 0.59899955, 0.5341011 ],
        [0.06873466, 0.09367422, 0.1702164 , 0.59879118, 0.80384419],
        [0.76987708, 0.87205879, 0.37017521, 0.43225566, 0.85086742]]])

In [41]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.99912861, 0.3753253 , 0.12319861, 0.86900372, 0.47174463],
       [0.54114496, 0.10191007, 0.60787885, 0.59469594, 0.14984536],
       [0.44268431, 0.90435483, 0.8754921 , 0.59899955, 0.5341011 ]])

In [42]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.72778316, 0.86900372, 0.12891798, 0.62696955],
       [0.21449398, 0.59469594, 0.66636484, 0.94173899],
       [0.4922534 , 0.59899955, 0.59879118, 0.43225566]])

### Indexação com booleanos

In [43]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[461,  13, 473, 333, 423, 355, 120, 317],
       [298, 380, 428, 437, 309, 358,  77,   4],
       [316,  84, 392, 474,  29,  29, 151, 262],
       [ 53, 224, 299, 258, 411, 417, 291, 472],
       [ 17, 264, 314, 357, 304, 235, 459, 281],
       [ 62,  66, 220,  20, 192, 373, 105, 254],
       [ 57, 363,  44, 352, 342, 342, 299,  43],
       [373, 337, 318,  68, 336, 145, 440, 340],
       [346, 247, 389,  50,  78, 259, 205, 348],
       [418, 293,   2,  77, 395,   9, 459, 339]])

In [44]:
a2D >= 250

array([[ True, False,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True,  True, False, False],
       [ True, False,  True,  True, False, False, False,  True],
       [False, False,  True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True, False,  True,  True],
       [False, False, False, False, False,  True, False,  True],
       [False,  True, False,  True,  True,  True,  True, False],
       [ True,  True,  True, False,  True, False,  True,  True],
       [ True, False,  True, False, False,  True, False,  True],
       [ True,  True, False, False,  True, False,  True,  True]])

In [45]:
a2D[a2D >= 250]

array([461, 473, 333, 423, 355, 317, 298, 380, 428, 437, 309, 358, 316,
       392, 474, 262, 299, 258, 411, 417, 291, 472, 264, 314, 357, 304,
       459, 281, 373, 254, 363, 352, 342, 342, 299, 373, 337, 318, 336,
       440, 340, 346, 389, 259, 348, 418, 293, 395, 459, 339])

In [46]:
a2D.mean()

257.3

In [47]:
a2D[a2D <= a2D.mean()]

array([ 13, 120,  77,   4,  84,  29,  29, 151,  53, 224,  17, 235,  62,
        66, 220,  20, 192, 105, 254,  57,  44,  43,  68, 145, 247,  50,
        78, 205,   2,  77,   9])