# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [2]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([ 54,  32, 130,  27, 198,  63,  64,  52, 182, 108, 146,  95])

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[123, 133,  64, 168],
       [ 58,   1,   9, 186],
       [187, 198,  39,  62]])

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[ 82, 161,  97, 197, 170, 101],
        [149,  10, 193,  54, 182, 173],
        [ 46,  59, 170,  24, 110,  25]],

       [[178,  90, 153,  66,  81,  83],
        [ 10, 175, 178,  73, 118, 174],
        [ 60,  88, 157,  43,   2,  49]]])

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1,  32, 130,  27, 198,  63,  64,  52, 182, 108, 146,  95])

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[123, 133,  64, 168],
       [ 58,   1,  -1, 186],
       [187, 198,  39,  62]])

In [7]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[ 82, 161,  97, 197, 170, 101],
        [149,  10, 193,  54, 182, 173],
        [ 46,  59, 170,  24, 110,  25]],

       [[178,  90, 153,  66,  81,  83],
        [ 10, 175, 178,  73, 118, 174],
        [ 60,  88, 157,  43,  -1,  49]]])

In [8]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1,  32, 130,  27, 198,  63,  64,  52, 182, 108, 146,  95, 100,
       130])

In [9]:
a1D # a1D não foi modificado

array([ -1,  32, 130,  27, 198,  63,  64,  52, 182, 108, 146,  95])

In [10]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([123, 133,  64, 168,  58,   1,  -1, 186, 187, 198,  39,  62, 100,
       130])

In [11]:
a2D # a2D não foi modificado

array([[123, 133,  64, 168],
       [ 58,   1,  -1, 186],
       [187, 198,  39,  62]])

In [12]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([ 82, 161,  97, 197, 170, 101, 149,  10, 193,  54, 182, 173,  46,
        59, 170,  24, 110,  25, 178,  90, 153,  66,  81,  83,  10, 175,
       178,  73, 118, 174,  60,  88, 157,  43,  -1,  49, 100, 130])

In [13]:
a3D # a3D não foi modificado

array([[[ 82, 161,  97, 197, 170, 101],
        [149,  10, 193,  54, 182, 173],
        [ 46,  59, 170,  24, 110,  25]],

       [[178,  90, 153,  66,  81,  83],
        [ 10, 175, 178,  73, 118, 174],
        [ 60,  88, 157,  43,  -1,  49]]])

In [14]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1  32 130  27 198  63  64  52 182 108 146  95 100 130]
[130 198  63  64  52 182 108 146  95 100 130]


### Comparação entre arrays

In [15]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [16]:
c1D = np.random.randint(1,10,20)
c1D

array([5, 1, 5, 5, 8, 8, 1, 2, 9, 3, 1, 1, 1, 9, 9, 1, 8, 9, 9, 4])

In [17]:
c1D == 5

array([ True, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [18]:
c1D[c1D == 5]

array([5, 5, 5])

### Operações entre arrays e escalares

In [19]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [23]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [25]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [26]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [27]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [28]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [29]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [30]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [31]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [32]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [33]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [34]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [35]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [36]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [38]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[ 14,  41,  77,  40,  42,  61,  80,  20,   8,   1],
       [  7,  58,  80,  59,  21,  57,  22,  18,  32,  89],
       [ 35,  60,  46, 100,  38,  37,  81,  39,  40,  30],
       [ 36,  74,  16,  61,  16,  28,  17,  93,  62,  97],
       [ 46,   8,  17,  20,  88,  78,  30,  83,  66,  20]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [39]:
# Soma de todos os elementos
d2D.sum()

2289

In [40]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([138, 241, 236, 280, 205, 261, 230, 253, 208, 237])

In [41]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([384, 443, 506, 500, 456])

In [42]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([138, 241, 236, 280, 205, 261, 230, 253, 208, 237])

In [43]:
# Retorna o menor valor geral
d2D.min()

1

In [44]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([ 7,  8, 16, 20, 16, 28, 17, 18,  8,  1])

In [45]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([ 1,  7, 30, 16,  8])

In [46]:
# Retorna o maior valor geral
d2D.max()

100

In [47]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([ 46,  74,  80, 100,  88,  78,  81,  93,  66,  97])

In [48]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([ 80,  89, 100,  97,  88])

In [49]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  14,   55,  132,  172,  214,  275,  355,  375,  383,  384,  391,
        449,  529,  588,  609,  666,  688,  706,  738,  827,  862,  922,
        968, 1068, 1106, 1143, 1224, 1263, 1303, 1333, 1369, 1443, 1459,
       1520, 1536, 1564, 1581, 1674, 1736, 1833, 1879, 1887, 1904, 1924,
       2012, 2090, 2120, 2203, 2269, 2289], dtype=int32)

In [50]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 14,  41,  77,  40,  42,  61,  80,  20,   8,   1],
       [ 21,  99, 157,  99,  63, 118, 102,  38,  40,  90],
       [ 56, 159, 203, 199, 101, 155, 183,  77,  80, 120],
       [ 92, 233, 219, 260, 117, 183, 200, 170, 142, 217],
       [138, 241, 236, 280, 205, 261, 230, 253, 208, 237]], dtype=int32)

In [51]:
d2D

array([[ 14,  41,  77,  40,  42,  61,  80,  20,   8,   1],
       [  7,  58,  80,  59,  21,  57,  22,  18,  32,  89],
       [ 35,  60,  46, 100,  38,  37,  81,  39,  40,  30],
       [ 36,  74,  16,  61,  16,  28,  17,  93,  62,  97],
       [ 46,   8,  17,  20,  88,  78,  30,  83,  66,  20]])

In [52]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 14,  55, 132, 172, 214, 275, 355, 375, 383, 384],
       [  7,  65, 145, 204, 225, 282, 304, 322, 354, 443],
       [ 35,  95, 141, 241, 279, 316, 397, 436, 476, 506],
       [ 36, 110, 126, 187, 203, 231, 248, 341, 403, 500],
       [ 46,  54,  71,  91, 179, 257, 287, 370, 436, 456]], dtype=int32)

In [53]:
# Retorna a média aritmética
d2D.mean()

45.78

In [54]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([27.6, 48.2, 47.2, 56. , 41. , 52.2, 46. , 50.6, 41.6, 47.4])

In [55]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([38.4, 44.3, 50.6, 50. , 45.6])

In [56]:
# Retorna o desvio padrão
d2D.std()

27.298564064800185

In [57]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([14.65059726, 22.66627451, 27.7517567 , 26.54053504, 25.47155276,
       17.79213309, 28.47455004, 31.56326979, 21.14332046, 38.46348918])

In [58]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([26.47715997, 26.66852077, 21.75408008, 29.96664813, 29.06613149])

In [59]:
# Retorna a mediana (geral)
np.median(d2D)

40.0

In [60]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([35., 58., 46., 59., 38., 57., 30., 39., 40., 30.])

In [61]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([40.5, 44.5, 39.5, 48.5, 38. ])

### Copiando e concatenando arrays

In [62]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[33, 30, 49,  2, 34],
       [26, 48,  1, 33, 42],
       [43,  6, 34,  5,  4],
       [22, 34, 43, 16,  6]])

In [63]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[68, 68, 65, 53, 72],
       [78, 69, 91, 50, 72],
       [55, 50, 61, 51, 97],
       [59, 74, 79, 72, 65]])

In [64]:
c2D = a2D
c2D

array([[33, 30, 49,  2, 34],
       [26, 48,  1, 33, 42],
       [43,  6, 34,  5,  4],
       [22, 34, 43, 16,  6]])

In [65]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[33, 30, 49, -1, 34],
       [26, 48, -1, 33, 42],
       [43, -1, 34, -1, -1],
       [22, 34, 43, -1, -1]])

In [66]:
a2D 

array([[33, 30, 49, -1, 34],
       [26, 48, -1, 33, 42],
       [43, -1, 34, -1, -1],
       [22, 34, 43, -1, -1]])

Os elementos de a2D também foram alterados. :-(

In [67]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[ 2, 11, 39, 30,  8],
       [16,  2, 39, 46, 41],
       [44,  6, 14, 43, 25],
       [22, 11, 20, 16, 15]])

In [68]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[ 2, 11, 39, 30,  8],
       [16,  2, 39, 46, 41],
       [44,  6, 14, 43, 25],
       [22, 11, 20, 16, 15]])

In [69]:
c2D[c2D < 20] = -1
c2D

array([[-1, -1, 39, 30, -1],
       [-1, -1, 39, 46, 41],
       [44, -1, -1, 43, 25],
       [22, -1, 20, -1, -1]])

In [70]:
a2D

array([[ 2, 11, 39, 30,  8],
       [16,  2, 39, 46, 41],
       [44,  6, 14, 43, 25],
       [22, 11, 20, 16, 15]])

Agora sim!!!

### Ordenando os elementos de um array

In [71]:
a1D = np.random.randint(1,100, 15)
a1D

array([24, 53, 88, 41, 99, 57, 14, 40, 71, 84, 89, 34, 21, 27, 59])

In [72]:
a1D.sort()
a1D

array([14, 21, 24, 27, 34, 40, 41, 53, 57, 59, 71, 84, 88, 89, 99])

In [73]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[65, 49, 78, 56, 61, 73, 27, 87, 52, 70],
       [98, 53, 85, 22, 36, 64, 20, 19, 10, 59],
       [58, 43, 96, 94, 43, 39, 49, 35, 33, 19],
       [82, 63, 22, 24, 92, 72, 10, 82, 57, 60],
       [59, 97, 69, 51, 86, 69, 38, 41, 72, 68],
       [17, 61, 66, 37, 31, 58, 88, 26, 15, 85]])

In [74]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[27, 49, 52, 56, 61, 65, 70, 73, 78, 87],
       [10, 19, 20, 22, 36, 53, 59, 64, 85, 98],
       [19, 33, 35, 39, 43, 43, 49, 58, 94, 96],
       [10, 22, 24, 57, 60, 63, 72, 82, 82, 92],
       [38, 41, 51, 59, 68, 69, 69, 72, 86, 97],
       [15, 17, 26, 31, 37, 58, 61, 66, 85, 88]])

In [75]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[10, 17, 20, 22, 36, 43, 49, 58, 78, 87],
       [10, 19, 24, 31, 37, 53, 59, 64, 82, 88],
       [15, 22, 26, 39, 43, 58, 61, 66, 85, 92],
       [19, 33, 35, 56, 60, 63, 69, 72, 85, 96],
       [27, 41, 51, 57, 61, 65, 70, 73, 86, 97],
       [38, 49, 52, 59, 68, 69, 72, 82, 94, 98]])

In [76]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[74, 85, 50, 36, 63, 66, 77, 39, 60, 19],
       [32, 97, 67, 92,  5, 73, 12, 83, 67, 24],
       [38, 57, 55, 57,  3, 78, 31,  2, 64, 48],
       [31, 63, 12, 36, 60, 87, 37, 37,  3,  9],
       [85, 69, 63, 36, 44, 34, 69, 19, 73, 66],
       [94, 83, 40,  8, 78, 67, 12, 22, 56, 93]])

In [77]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[19, 36, 39, 50, 60, 63, 66, 74, 77, 85],
       [ 5, 12, 24, 32, 67, 67, 73, 83, 92, 97],
       [ 2,  3, 31, 38, 48, 55, 57, 57, 64, 78],
       [ 3,  9, 12, 31, 36, 37, 37, 60, 63, 87],
       [19, 34, 36, 44, 63, 66, 69, 69, 73, 85],
       [ 8, 12, 22, 40, 56, 67, 78, 83, 93, 94]])

### Transposição de arrays

In [78]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [80]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [82]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [83]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [84]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [85]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [86]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [88]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [89]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [90]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[44, 69, 48, 68, 97, 59, 87, 82, 80],
       [95, 68,  9, 24, 50, 19, 85, 78, 59],
       [12, 54, 63, 98, 83, 27, 82, 24,  1]])

In [91]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[ 92,  70, 100,  95,  74,  15,  36,  97,  41],
       [ 12,  68,  30,  79,  61,  87,  31,  50,  25],
       [ 10,  13,   7,  47,  57,  10,  69,  31,   7],
       [ 94,  61,  31,  13,  71,  86,  33,  39,  91],
       [ 38,  25,  66,  55,  74,  82,   6,  25,  80]])

In [92]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[40, 29, 42, 65],
       [86, 37, 64, 63],
       [ 4, 83, 39, 26],
       [ 3, 58, 65, 21],
       [ 1, 51, 25, 19]])

In [93]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [95]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [96]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[44 69 48 68 97 59 87 82 80]
 [95 68  9 24 50 19 85 78 59]
 [12 54 63 98 83 27 82 24  1]]

b2D
[[ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]

Concatenação
[[ 44  69  48  68  97  59  87  82  80]
 [ 95  68   9  24  50  19  85  78  59]
 [ 12  54  63  98  83  27  82  24   1]
 [ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]


In [97]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[44 69 48 68 97 59 87 82 80]
 [95 68  9 24 50 19 85 78 59]
 [12 54 63 98 83 27 82 24  1]]

b2D
[[ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]

Concatenação
[[ 44  69  48  68  97  59  87  82  80]
 [ 95  68   9  24  50  19  85  78  59]
 [ 12  54  63  98  83  27  82  24   1]
 [ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]


In [98]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]

c2D
[[40 29 42 65]
 [86 37 64 63]
 [ 4 83 39 26]
 [ 3 58 65 21]
 [ 1 51 25 19]]

Concatenação
[[ 92  70 100  95  74  15  36  97  41  40  29  42  65]
 [ 12  68  30  79  61  87  31  50  25  86  37  64  63]
 [ 10  13   7  47  57  10  69  31   7   4  83  39  26]
 [ 94  61  31  13  71  86  33  39  91   3  58  65  21]
 [ 38  25  66  55  74  82   6  25  80   1  51  25  19]]


In [99]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]

c2D
[[40 29 42 65]
 [86 37 64 63]
 [ 4 83 39 26]
 [ 3 58 65 21]
 [ 1 51 25 19]]

Concatenação
[[ 92  70 100  95  74  15  36  97  41  40  29  42  65]
 [ 12  68  30  79  61  87  31  50  25  86  37  64  63]
 [ 10  13   7  47  57  10  69  31   7   4  83  39  26]
 [ 94  61  31  13  71  86  33  39  91   3  58  65  21]
 [ 38  25  66  55  74  82   6  25  80   1  51  25  19]]


### Dividindo arrays

In [100]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[ 44  69  48  68  97  59  87  82  80]
 [ 95  68   9  24  50  19  85  78  59]
 [ 12  54  63  98  83  27  82  24   1]
 [ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]

1a parte
[[ 44  69  48  68  97  59  87  82  80]
 [ 95  68   9  24  50  19  85  78  59]
 [ 12  54  63  98  83  27  82  24   1]
 [ 92  70 100  95  74  15  36  97  41]]

2a parte
[[12 68 30 79 61 87 31 50 25]
 [10 13  7 47 57 10 69 31  7]
 [94 61 31 13 71 86 33 39 91]
 [38 25 66 55 74 82  6 25 80]]


In [101]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[ 44  69  48  68  97  59  87  82  80]
 [ 95  68   9  24  50  19  85  78  59]
 [ 12  54  63  98  83  27  82  24   1]
 [ 92  70 100  95  74  15  36  97  41]
 [ 12  68  30  79  61  87  31  50  25]
 [ 10  13   7  47  57  10  69  31   7]
 [ 94  61  31  13  71  86  33  39  91]
 [ 38  25  66  55  74  82   6  25  80]]

1a parte
[[ 44  69  48]
 [ 95  68   9]
 [ 12  54  63]
 [ 92  70 100]
 [ 12  68  30]
 [ 10  13   7]
 [ 94  61  31]
 [ 38  25  66]]

2a parte
[[68 97 59]
 [24 50 19]
 [98 83 27]
 [95 74 15]
 [79 61 87]
 [47 57 10]
 [13 71 86]
 [55 74 82]]

3a parte
[[87 82 80]
 [85 78 59]
 [82 24  1]
 [36 97 41]
 [31 50 25]
 [69 31  7]
 [33 39 91]
 [ 6 25 80]]
